// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';


function concat(a, b) {
  return /* record */[
          /* width */a[/* width */0] + b[/* width */0],
          /* min */a[/* min */1] + b[/* min */1],
          /* max */a[/* max */2] + b[/* max */2]
        ];
}

function t_of_box(param) {
  var width = param[/* width */0];
  return /* record */[
          /* width */width,
          /* min */width,
          /* max */width
        ];
}

function t_of_glue(param) {
  var width = param[/* width */0];
  return /* record */[
          /* width */width,
          /* min */width - param[/* shrinkability */2],
          /* max */width + param[/* stretchability */1]
        ];
}

function measure(els) {
  var _es = els;
  var _acc = /* record */[
    /* width */0,
    /* min */0,
    /* max */0
  ];
  while(true) {
    var acc = _acc;
    var es = _es;
    if (es) {
      var match = es[0];
      switch (match.tag | 0) {
        case 0 : 
            _acc = concat(acc, t_of_box(match[0]));
            _es = es[1];
            continue ;
        case 1 : 
            _acc = concat(acc, t_of_glue(match[0]));
            _es = es[1];
            continue ;
        case 2 : 
            _es = es[1];
            continue ;
        
      }
    } else {
      return acc;
    }
  };
}

var MeasuredWidth = [measure];

exports.MeasuredWidth = MeasuredWidth;
/* No side effect */
